droplet_name: "videopoint"
global_dest_path: "../"
do_state: absent
do_loop_droplet_name:
  - "www1"
  - "www2"
do_api_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66373237613866623863316339376433306238663236376133646461666333626635356666656665
  6536386232616563326534646236383235636162643535390a646435626537646634323236393737
  32323565613138333262326638613462616364616637316633366436663630623065356538326232
  3762353930656139330a633263366132656463303432663033393330643562303430393938313934
  32383365356166316539303832633435646666626461313566346164386364623861636137396431
  36623361386135326335313966663066636531636137616431313434303961373062363039616461
  66663239633332333931373134623330373331323732643365343765303235663438326332613837
  30376134363834366539